#!/usr/bin/env node
/**
 * Apply picks.json (from picker.html's Export button) to the app:
 *   1. copy each chosen frame to public/images/burritos/<slug>.jpg
 *   2. geocode each place's address via Nominatim (cached in data/geocache.json)
 *   3. regenerate data/burritos.ts with the real scraped data
 *
 * Usage: node apply-picks.mjs [path/to/picks.json]
 * Default picks path: ~/Downloads/picks.json
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const app = join(root, "..");
const picksPath = process.argv[2] ?? join(homedir(), "Downloads/picks.json");
if (!existsSync(picksPath)) {
  console.error(`no picks file at ${picksPath}. Export from picker.html first.`);
  process.exit(1);
}
const picks = JSON.parse(readFileSync(picksPath, "utf8"));
const videos = Object.fromEntries(
  readFileSync(join(root, "data/videos.jsonl"), "utf8")
    .trim()
    .split("\n")
    .map((l) => JSON.parse(l))
    .map((v) => [v.id, v])
);

const cachePath = join(root, "data/geocache.json");
const geocache = existsSync(cachePath) ? JSON.parse(readFileSync(cachePath, "utf8")) : {};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function geocodeOne(q) {
  if (q in geocache && geocache[q]) return geocache[q];
  const url = `https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(q)}`;
  const res = await fetch(url, { headers: { "User-Agent": "bbc-burrito-app/1.0 (jen@tryscope.app)" } });
  const [hit] = await res.json();
  const coords = hit ? { lat: +(+hit.lat).toFixed(5), lng: +(+hit.lon).toFixed(5) } : null;
  geocache[q] = coords;
  writeFileSync(cachePath, JSON.stringify(geocache, null, 2));
  await sleep(1100); // Nominatim rate limit: 1 req/s
  return coords;
}

async function geocode(poi) {
  // full address first, then a looser "name, city, CA" query
  return (
    (poi.address && (await geocodeOne(poi.address))) ||
    (await geocodeOne(`${poi.name}, ${poi.city || "Bay Area"}, California`))
  );
}

const imgDir = join(app, "public/images/burritos");
mkdirSync(imgDir, { recursive: true });

const cleanNotes = (desc) =>
  desc.replace(/#\w+/g, "").replace(/@[\w.❗️]+/g, "").replace(/\s+/g, " ").trim();

// one entry per place: when he reviewed a taqueria more than once, keep
// the picked video with the most plays
const bySlug = new Map();
for (const [dir, pick] of Object.entries(picks)) {
  if (pick.skip || !pick.frame) continue;
  const id = dir.split("-").at(-1);
  const v = videos[id];
  if (!v) {
    console.warn(`no scraped data for ${dir}, skipping`);
    continue;
  }
  if (!v.poi) {
    console.warn(`no tagged place on ${dir}, skipping`);
    continue;
  }
  const slug = dir.replace(`-${id}`, "");
  const prev = bySlug.get(slug);
  if (!prev || (v.plays ?? 0) > (prev.v.plays ?? 0)) bySlug.set(slug, { dir, pick, id, v });
}

const entries = [];
for (const { dir, pick, id, v } of bySlug.values()) {
  const slug = dir.replace(`-${id}`, "");
  copyFileSync(join(app, "assets/frames", dir, pick.frame), join(imgDir, `${slug}.jpg`));
  const coords = await geocode(v.poi);
  if (!coords) console.warn(`geocode miss for ${v.poi?.name}: using 0,0 (fix manually)`);
  const rating = v.desc.match(/(\d+(?:\.\d+)?)\s*\/\s*10/)?.[1];
  entries.push({
    id: slug,
    name: rating ? `${rating}/10 burrito` : "Burrito",
    taqueria: v.poi?.name ?? slug,
    neighborhood: v.poi?.city ?? "Bay Area",
    tier: pick.tier,
    fluffieNotes: cleanNotes(v.desc),
    lat: coords?.lat ?? 0,
    lng: coords?.lng ?? 0,
    imgUrl: `/images/burritos/${slug}.jpg`,
    videoUrl: `https://www.tiktok.com/@fluffie.donut/video/${id}`,
    plays: v.plays,
  });
  console.log(`ok ${slug} (${pick.tier}) ${coords ? "" : "NO COORDS"}`);
}

const tierOrder = { S: 0, A: 1, B: 2, C: 3, D: 4, F: 5 };
entries.sort((a, b) => tierOrder[a.tier] - tierOrder[b.tier] || b.plays - a.plays);

const ts = `// GENERATED by analyzer/apply-picks.mjs from @fluffie.donut TikTok data.
// Edit picks in assets/picker.html and rerun; do not hand-edit entries.
export type Tier = "S" | "A" | "B" | "C" | "D" | "F";

export interface Burrito {
  id: string;
  name: string;
  taqueria: string;
  neighborhood: string;
  tier: Tier;
  fluffieNotes: string; // caption, hashtags stripped
  beliRating?: number; // Jen's Beli score, hand-added
  lat: number;
  lng: number;
  imgUrl: string;
  videoUrl?: string;
  plays?: number;
}

export const TIERS: Tier[] = ["S", "A", "B", "C", "D", "F"];

export const TIER_COLORS: Record<Tier, string> = {
  S: "var(--tier-s)",
  A: "var(--tier-a)",
  B: "var(--tier-b)",
  C: "var(--tier-c)",
  D: "var(--tier-d)",
  F: "var(--tier-f)",
};

export const BURRITOS: Burrito[] = ${JSON.stringify(entries, null, 2)};
`;
writeFileSync(join(app, "data/burritos.ts"), ts);
console.log(`\nwrote data/burritos.ts with ${entries.length} burritos + ${Object.values(picks).filter((p) => p.skip).length} skipped`);
