// GENERATED by analyzer/apply-picks.mjs from @fluffie.donut TikTok data.
// Edit picks in assets/picker.html and rerun; do not hand-edit entries.
export type Tier = "S" | "A" | "B" | "C" | "D" | "F";

export interface Burrito {
  id: string;
  name: string;
  taqueria: string;
  neighborhood: string;
  tier: Tier;
  fluffieNotes: string; // caption, hashtags stripped
  beliRating?: number; // Jen's Beli score, hand-added
  lat: number;
  lng: number;
  imgUrl: string;
  videoUrl?: string;
  plays?: number;
}

export const TIERS: Tier[] = ["S", "A", "B", "C", "D", "F"];

export const TIER_COLORS: Record<Tier, string> = {
  S: "var(--tier-s)",
  A: "var(--tier-a)",
  B: "var(--tier-b)",
  C: "var(--tier-c)",
  D: "var(--tier-d)",
  F: "var(--tier-f)",
};

export const BURRITOS: Burrito[] = [
  {
    "id": "el-farolito-mission-street-flagship",
    "name": "Burrito",
    "taqueria": "El Farolito Mission Street (Flagship)",
    "neighborhood": "San Francisco",
    "tier": "S",
    "fluffieNotes": "best. burrito. ever. ❕",
    "lat": 37.75267,
    "lng": -122.41824,
    "imgUrl": "/images/burritos/el-farolito-mission-street-flagship.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7510631790583794975",
    "plays": 168000
  },
  {
    "id": "taqueria-el-paisa",
    "name": "Burrito",
    "taqueria": "Taqueria El Paisa",
    "neighborhood": "Berkeley",
    "tier": "S",
    "fluffieNotes": "the worlds biggest burrito?",
    "lat": 37.77085,
    "lng": -122.21121,
    "imgUrl": "/images/burritos/taqueria-el-paisa.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7662436933238263070",
    "plays": 69200
  },
  {
    "id": "los-gallos-taqueria",
    "name": "Burrito",
    "taqueria": "Los Gallos Taqueria",
    "neighborhood": "Redwood City",
    "tier": "S",
    "fluffieNotes": "best burrito in menlo park 🥰😛",
    "lat": 37.47848,
    "lng": -122.18692,
    "imgUrl": "/images/burritos/los-gallos-taqueria.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7579668343653764383",
    "plays": 51100
  },
  {
    "id": "marsh-manor-shopping-center",
    "name": "Burrito",
    "taqueria": "Marsh Manor Shopping Center",
    "neighborhood": "Redwood City",
    "tier": "S",
    "fluffieNotes": "los gallos is a must try",
    "lat": 37.47859,
    "lng": -122.18761,
    "imgUrl": "/images/burritos/marsh-manor-shopping-center.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7507270281702935839",
    "plays": 35800
  },
  {
    "id": "spartan-taco-truck",
    "name": "Burrito",
    "taqueria": "Spartan Taco Truck",
    "neighborhood": "San Jose",
    "tier": "A",
    "fluffieNotes": "spartan taco truck is ok",
    "lat": 37.33315,
    "lng": -121.87587,
    "imgUrl": "/images/burritos/spartan-taco-truck.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7525511186650041630",
    "plays": 110500
  },
  {
    "id": "el-grullense",
    "name": "Burrito",
    "taqueria": "El Grullense",
    "neighborhood": "Redwood City",
    "tier": "A",
    "fluffieNotes": "la lengua at el grullense",
    "lat": 37.48387,
    "lng": -122.22514,
    "imgUrl": "/images/burritos/el-grullense.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7513962900814318878",
    "plays": 97000
  },
  {
    "id": "taqueria-los-pericos",
    "name": "Burrito",
    "taqueria": "Taqueria Los Pericos",
    "neighborhood": "Santa Cruz",
    "tier": "A",
    "fluffieNotes": "best burrito in santa cruz",
    "lat": 36.97708,
    "lng": -122.02671,
    "imgUrl": "/images/burritos/taqueria-los-pericos.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7539282445980503327",
    "plays": 94400
  },
  {
    "id": "tacos-chencho",
    "name": "Burrito",
    "taqueria": "Tacos Chencho",
    "neighborhood": "San Jose",
    "tier": "A",
    "fluffieNotes": "chenchos 6 for 22",
    "lat": 37.30248,
    "lng": -121.9318,
    "imgUrl": "/images/burritos/tacos-chencho.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7528503833341840671",
    "plays": 75200
  },
  {
    "id": "taqueria-el-farolito",
    "name": "Burrito",
    "taqueria": "Taqueria El Farolito",
    "neighborhood": "South San Francisco",
    "tier": "A",
    "fluffieNotes": "what a bargain - farolito is fluffie approved",
    "lat": 37.65578,
    "lng": -122.41221,
    "imgUrl": "/images/burritos/taqueria-el-farolito.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7532884452599516447",
    "plays": 61800
  },
  {
    "id": "los-altos-taqueria-mexican-inc",
    "name": "Burrito",
    "taqueria": "Los Altos Taqueria Mexican Inc",
    "neighborhood": "Mountain View",
    "tier": "A",
    "fluffieNotes": "los alto taqueria sopping burrito",
    "lat": 37.41408,
    "lng": -122.09318,
    "imgUrl": "/images/burritos/los-altos-taqueria-mexican-inc.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7530669521422519582",
    "plays": 59700
  },
  {
    "id": "tacos-el-patron",
    "name": "Burrito",
    "taqueria": "Tacos El Patron",
    "neighborhood": "San Francisco",
    "tier": "A",
    "fluffieNotes": "best birria?",
    "lat": 37.74906,
    "lng": -122.41615,
    "imgUrl": "/images/burritos/tacos-el-patron.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7665390514061036831",
    "plays": 1068
  },
  {
    "id": "san-mateo-taqueria",
    "name": "Burrito",
    "taqueria": "San Mateo Taqueria",
    "neighborhood": "San Mateo",
    "tier": "B",
    "fluffieNotes": "one dollar tacos and bones in san mateo only this august!",
    "lat": 37.54332,
    "lng": -122.30857,
    "imgUrl": "/images/burritos/san-mateo-taqueria.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7537349173629177118",
    "plays": 119100
  },
  {
    "id": "la-hacienda-market",
    "name": "Burrito",
    "taqueria": "La Hacienda Market",
    "neighborhood": "Palo Alto",
    "tier": "B",
    "fluffieNotes": "hidden gem in menlo park",
    "lat": 37.45942,
    "lng": -122.1527,
    "imgUrl": "/images/burritos/la-hacienda-market.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7591235478645493022",
    "plays": 60600
  },
  {
    "id": "berkeley-bowl-west",
    "name": "Burrito",
    "taqueria": "Berkeley Bowl West",
    "neighborhood": "Berkeley",
    "tier": "B",
    "fluffieNotes": "best burrito in berkeley is at ... berkeley bowl!",
    "lat": 37.8534,
    "lng": -122.29036,
    "imgUrl": "/images/burritos/berkeley-bowl-west.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7503939910332730655",
    "plays": 56200
  },
  {
    "id": "taquer-a-santa-cruz",
    "name": "Burrito",
    "taqueria": "Taquería Santa Cruz",
    "neighborhood": "Santa Cruz",
    "tier": "B",
    "fluffieNotes": "best burrito in santa cruz?",
    "lat": 36.96154,
    "lng": -122.04579,
    "imgUrl": "/images/burritos/taquer-a-santa-cruz.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7546755777084624158",
    "plays": 42100
  },
  {
    "id": "il-canto-cafe",
    "name": "Burrito",
    "taqueria": "Il Canto Cafe",
    "neighborhood": "San Francisco",
    "tier": "B",
    "fluffieNotes": "possibly the second best breakup burrito in the city? i think so",
    "lat": 37.79398,
    "lng": -122.40063,
    "imgUrl": "/images/burritos/il-canto-cafe.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7661737312610422047",
    "plays": 41200
  },
  {
    "id": "taqueria-guadalajara-grill",
    "name": "Burrito",
    "taqueria": "Taqueria Guadalajara Grill",
    "neighborhood": "Davis",
    "tier": "B",
    "fluffieNotes": "the best breakfast burrito is just a normal burrito",
    "lat": 38.55012,
    "lng": -121.69588,
    "imgUrl": "/images/burritos/taqueria-guadalajara-grill.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7586747905260752159",
    "plays": 31600
  },
  {
    "id": "tacos-los-gemelos",
    "name": "Burrito",
    "taqueria": "Tacos Los Gemelos",
    "neighborhood": "Redwood City",
    "tier": "B",
    "fluffieNotes": "hand made tortillas at gemelos",
    "lat": 37.47929,
    "lng": -122.22608,
    "imgUrl": "/images/burritos/tacos-los-gemelos.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7641344553332608287",
    "plays": 19500
  },
  {
    "id": "chavez-supermarket",
    "name": "Burrito",
    "taqueria": "Chavez Supermarket",
    "neighborhood": "San Jose",
    "tier": "B",
    "fluffieNotes": "chavez taqueria is gas",
    "lat": 37.36555,
    "lng": -121.84935,
    "imgUrl": "/images/burritos/chavez-supermarket.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7536600700046871838",
    "plays": 15100
  },
  {
    "id": "taqueria-el-grullense-m-g",
    "name": "Burrito",
    "taqueria": "Taqueria El Grullense M&G",
    "neighborhood": "Mountain View",
    "tier": "B",
    "fluffieNotes": "pretty good tacos in palo alto",
    "lat": 37.41817,
    "lng": -122.13321,
    "imgUrl": "/images/burritos/taqueria-el-grullense-m-g.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7539977618339220766",
    "plays": 13800
  },
  {
    "id": "taqueria-la-cazuela",
    "name": "Burrito",
    "taqueria": "Taqueria La Cazuela",
    "neighborhood": "Mountain View",
    "tier": "B",
    "fluffieNotes": "tasty burrito but why cut in half?",
    "lat": 37.47134,
    "lng": -122.13482,
    "imgUrl": "/images/burritos/taqueria-la-cazuela.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7665023278863437087",
    "plays": 9606
  },
  {
    "id": "chuy-s-fiestas",
    "name": "Burrito",
    "taqueria": "Chuy's Fiestas",
    "neighborhood": "San Francisco",
    "tier": "B",
    "fluffieNotes": "beli had a fire burrito req",
    "lat": 37.75985,
    "lng": -122.41455,
    "imgUrl": "/images/burritos/chuy-s-fiestas.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7652393649514319134",
    "plays": 3629
  },
  {
    "id": "tacos-sinaloa",
    "name": "Burrito",
    "taqueria": "Tacos Sinaloa",
    "neighborhood": "Berkeley",
    "tier": "C",
    "fluffieNotes": "a light lunch in berkeley",
    "lat": 37.86716,
    "lng": -122.25898,
    "imgUrl": "/images/burritos/tacos-sinaloa.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7544438722507377950",
    "plays": 59000
  },
  {
    "id": "la-taqueria",
    "name": "Burrito",
    "taqueria": "La Taqueria",
    "neighborhood": "San Francisco",
    "tier": "C",
    "fluffieNotes": "Taco Fiend is my inspiration",
    "lat": 37.75089,
    "lng": -122.41807,
    "imgUrl": "/images/burritos/la-taqueria.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7529926498069859615",
    "plays": 31800
  },
  {
    "id": "berkeley",
    "name": "Burrito",
    "taqueria": "Berkeley",
    "neighborhood": "",
    "tier": "C",
    "fluffieNotes": "raleigh's taco tuesday complements of a new videographer",
    "lat": 36.70146,
    "lng": -118.756,
    "imgUrl": "/images/burritos/berkeley.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7501525751582215454",
    "plays": 31700
  },
  {
    "id": "taqueria-pancho-villa",
    "name": "Burrito",
    "taqueria": "Taqueria Pancho Villa",
    "neighborhood": "San Mateo",
    "tier": "C",
    "fluffieNotes": "pancho villa feast - back in the bay!",
    "lat": 37.56505,
    "lng": -122.3216,
    "imgUrl": "/images/burritos/taqueria-pancho-villa.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7575221426622434590",
    "plays": 26200
  },
  {
    "id": "las-caba-as-mexican-grill-taqueria",
    "name": "Burrito",
    "taqueria": "Las Cabañas Mexican Grill & Taqueria",
    "neighborhood": "Berkeley",
    "tier": "C",
    "fluffieNotes": "best burrito in berkeley?",
    "lat": 37.87288,
    "lng": -122.27333,
    "imgUrl": "/images/burritos/las-caba-as-mexican-grill-taqueria.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7576707931807239454",
    "plays": 20100
  },
  {
    "id": "raleigh-s-pub",
    "name": "Burrito",
    "taqueria": "Raleigh's Pub",
    "neighborhood": "Berkeley",
    "tier": "C",
    "fluffieNotes": "back at raleigh's - come say hi",
    "lat": 37.86627,
    "lng": -122.25886,
    "imgUrl": "/images/burritos/raleigh-s-pub.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7504109953884409119",
    "plays": 17900
  },
  {
    "id": "sancho-s-taqueria",
    "name": "Burrito",
    "taqueria": "Sancho's Taqueria",
    "neighborhood": "Mountain View",
    "tier": "C",
    "fluffieNotes": "TRADITION at sanchos",
    "lat": 37.44896,
    "lng": -122.16085,
    "imgUrl": "/images/burritos/sancho-s-taqueria.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7525094179618295071",
    "plays": 17600
  },
  {
    "id": "gordo-taqueria",
    "name": "Burrito",
    "taqueria": "Gordo Taqueria",
    "neighborhood": "Berkeley",
    "tier": "C",
    "fluffieNotes": "a tasty burrito in berkeley",
    "lat": 37.85734,
    "lng": -122.25302,
    "imgUrl": "/images/burritos/gordo-taqueria.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7585628847723285790",
    "plays": 17400
  },
  {
    "id": "taqueria-guadalajara",
    "name": "Burrito",
    "taqueria": "Taqueria Guadalajara",
    "neighborhood": "San Francisco",
    "tier": "C",
    "fluffieNotes": "what's the best in sf?",
    "lat": 37.72147,
    "lng": -122.43754,
    "imgUrl": "/images/burritos/taqueria-guadalajara.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7538869919639817502",
    "plays": 15700
  },
  {
    "id": "los-carnalitos-food-truck",
    "name": "Burrito",
    "taqueria": "Los Carnalitos Food Truck",
    "neighborhood": "Redwood City",
    "tier": "C",
    "fluffieNotes": "street burrito - got pastor this time.",
    "lat": 37.46924,
    "lng": -122.21127,
    "imgUrl": "/images/burritos/los-carnalitos-food-truck.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7656108276404194590",
    "plays": 15100
  },
  {
    "id": "tacos-el-jarochito",
    "name": "Burrito",
    "taqueria": "Tacos El Jarochito",
    "neighborhood": "Palo Alto",
    "tier": "C",
    "fluffieNotes": "jarochito lol",
    "lat": 37.4571,
    "lng": -122.16906,
    "imgUrl": "/images/burritos/tacos-el-jarochito.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7656467830723857694",
    "plays": 13100
  },
  {
    "id": "breakfast-little",
    "name": "Burrito",
    "taqueria": "Breakfast Little",
    "neighborhood": "San Francisco",
    "tier": "C",
    "fluffieNotes": "breaky little breaks burrito",
    "lat": 37.75522,
    "lng": -122.42036,
    "imgUrl": "/images/burritos/breakfast-little.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7663593028732439839",
    "plays": 5425
  },
  {
    "id": "puentez-taqueria",
    "name": "Burrito",
    "taqueria": "Puentez Taqueria",
    "neighborhood": "San Rafael",
    "tier": "D",
    "fluffieNotes": "mid in marin",
    "lat": 37.96939,
    "lng": -122.51577,
    "imgUrl": "/images/burritos/puentez-taqueria.jpg",
    "videoUrl": "https://www.tiktok.com/@fluffie.donut/video/7660580895916608798",
    "plays": 16100
  }
];
